import { ArrowLeft } from "lucide-react";
import { Link } from "react-router-dom";

export function TermsPage() {
  return (
    <div className="min-h-screen bg-background">
      {/* Header */}
      <header className="border-b bg-card/50 backdrop-blur-sm sticky top-0 z-10">
        <div className="max-w-4xl mx-auto px-4 py-4 flex items-center gap-4">
          <Link
            to="/login"
            className="inline-flex items-center gap-2 text-sm text-muted-foreground hover:text-foreground transition-colors"
          >
            <ArrowLeft className="w-4 h-4" />
            Back
          </Link>
          <h1 className="text-lg font-semibold">Terms of Service</h1>
        </div>
      </header>

      {/* Content */}
      <main className="max-w-4xl mx-auto px-4 py-8">
        <div className="prose prose-neutral dark:prose-invert max-w-none">
          <p className="text-sm text-muted-foreground">
            Last updated: February 12, 2026
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">1. Acceptance</h2>
          <p>
            By accessing or using Product OS at{" "}
            <strong>productos.dev</strong> (the &quot;Service&quot;), you agree
            to be bound by these Terms of Service (&quot;Terms&quot;). If you do
            not agree, you must not use the Service.
          </p>
          <p>
            The Service is operated by{" "}
            <strong>b25 Ventures UG (haftungsbeschr&auml;nkt)</strong>,
            Kaltenberg 3, 63776 M&ouml;mbris, Germany (&quot;we&quot;,
            &quot;us&quot;, &quot;our&quot;).
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            2. Service Description
          </h2>
          <p>
            Product OS is an AI-powered product management platform that helps
            users process product ideas through specialized AI agents. The
            Service is currently in <strong>beta</strong> and may change
            significantly as we iterate.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            3. Account &amp; Eligibility
          </h2>
          <p>
            You must be at least 16 years old to use the Service. By creating an
            account, you represent that:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>You are at least 16 years of age</li>
            <li>
              The information you provide is accurate and complete
            </li>
            <li>
              You will keep your account credentials secure and not share them
              with others
            </li>
            <li>
              You are responsible for all activity that occurs under your account
            </li>
          </ul>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            4. Acceptable Use
          </h2>
          <p>You agree not to:</p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              Use the Service for any illegal or unauthorized purpose
            </li>
            <li>
              Upload, submit, or generate content that violates any applicable
              law or regulation
            </li>
            <li>
              Reverse engineer, decompile, or disassemble any part of the
              Service
            </li>
            <li>
              Scrape, crawl, or use automated means to access the Service
              without our written permission
            </li>
            <li>
              Submit restricted data (health data, government IDs, payment card
              details, or other sensitive personal data) unless your workspace is
              explicitly configured for it &mdash; see our{" "}
              <Link to="/restricted-data" className="underline hover:text-foreground">
                Restricted Data Notice
              </Link>
            </li>
            <li>
              Use AI-generated outputs to create spam, misleading content, or to
              impersonate others
            </li>
            <li>
              Attempt to circumvent rate limits, access controls, or security
              measures
            </li>
          </ul>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            5. Intellectual Property
          </h2>
          <p>
            <strong>Your content:</strong> You retain ownership of all inputs,
            product ideas, and data you submit to the Service.
          </p>
          <p>
            <strong>AI-generated outputs:</strong> Outputs generated by AI
            agents are provided &quot;as is&quot;. You may use them for any
            lawful purpose. We do not claim ownership of AI-generated outputs,
            but we make no guarantees regarding their originality, accuracy, or
            fitness for a particular purpose.
          </p>
          <p>
            <strong>Platform IP:</strong> The Service, including its design,
            code, AI agent architecture, and branding, remains our intellectual
            property. These Terms do not grant you any rights to our trademarks,
            logos, or other brand features.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            6. AI Disclaimer
          </h2>
          <p>
            The Service uses artificial intelligence to generate content
            including product strategies, specifications, market analyses, and
            other outputs. You acknowledge that:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>
              AI-generated outputs may contain errors, inaccuracies, or
              hallucinations
            </li>
            <li>
              Outputs do not constitute professional advice (legal, financial,
              medical, or otherwise)
            </li>
            <li>
              You are solely responsible for reviewing, validating, and deciding
              whether to act on any AI-generated content
            </li>
            <li>
              We are not liable for decisions made based on AI-generated outputs
            </li>
          </ul>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            7. Data Processing
          </h2>
          <p>
            Our processing of your personal data is governed by our{" "}
            <Link to="/privacy" className="underline hover:text-foreground">
              Privacy Policy
            </Link>
            . The data controller is b25 Ventures UG (haftungsbeschr&auml;nkt).
          </p>
          <p>
            By using the Service, you acknowledge that your data may be
            processed by third-party AI providers as described in our Privacy
            Policy.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            8. Availability &amp; Beta
          </h2>
          <p>
            The Service is provided on an &quot;as is&quot; and &quot;as
            available&quot; basis. During the beta period:
          </p>
          <ul className="list-disc pl-6 space-y-1">
            <li>We do not guarantee any specific uptime or SLA</li>
            <li>
              Features may be added, changed, or removed without prior notice
            </li>
            <li>
              We may limit access, introduce usage caps, or modify the
              Service at our discretion
            </li>
            <li>
              Data loss may occur &mdash; we recommend keeping copies of
              important outputs
            </li>
          </ul>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            9. Limitation of Liability
          </h2>
          <p>
            To the extent permitted by applicable law, our total liability for
            all claims arising from or related to the Service is limited to the
            amount you paid us in the 12 months preceding the claim (or EUR 100,
            whichever is greater).
          </p>
          <p>
            This limitation does not apply to liability for intent
            (Vorsatz) or gross negligence (grobe Fahrl&auml;ssigkeit), or to
            liability for damages resulting from injury to life, body, or health,
            or any other liability that cannot be excluded under German law.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            10. Termination
          </h2>
          <p>
            Either party may terminate this agreement at any time. You may stop
            using the Service and request account deletion. We may suspend or
            terminate your access if you violate these Terms or for any other
            reason with reasonable notice.
          </p>
          <p>
            Upon termination, your data will be handled in accordance with our{" "}
            <Link to="/privacy" className="underline hover:text-foreground">
              Privacy Policy
            </Link>{" "}
            (data retention and deletion provisions).
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            11. Governing Law &amp; Jurisdiction
          </h2>
          <p>
            These Terms are governed by the laws of the Federal Republic of
            Germany. The exclusive place of jurisdiction for all disputes arising
            from or in connection with these Terms is Aschaffenburg, Germany,
            to the extent permitted by law.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">
            12. Changes to These Terms
          </h2>
          <p>
            We may update these Terms from time to time. For material changes,
            we will provide at least 30 days&apos; notice via email or an in-app
            notification before the new terms take effect. Continued use of the
            Service after the notice period constitutes acceptance of the
            updated Terms.
          </p>

          <h2 className="text-xl font-semibold mt-8 mb-4">13. Contact</h2>
          <p>
            If you have questions about these Terms, contact us at:
          </p>
          <ul className="list-none pl-0 space-y-1 mt-4">
            <li>
              <strong>b25 Ventures UG (haftungsbeschr&auml;nkt)</strong>
            </li>
            <li>Kaltenberg 3, 63776 M&ouml;mbris, Germany</li>
            <li>
              <strong>Email:</strong>{" "}
              <a
                href="mailto:hello@andreaswissel.com"
                className="underline hover:text-foreground"
              >
                hello@andreaswissel.com
              </a>
            </li>
            <li>
              <strong>Gesch&auml;ftsf&uuml;hrer:</strong> Andreas Wissel
            </li>
          </ul>
        </div>
      </main>
    </div>
  );
}
