export const MOCK_DISCOVERY_CLUSTERS = [
  {
    id: "mock-1",
    runId: "mock-run",
    userId: "",
    title: "Search is broken — users can't find reports or features",
    summary: "Multiple signals from customers, support, and internal teams converge on a critical search/navigation failure. Users spend excessive time finding content, leading to churn risk and deal losses.",
    featureSuggestion: "Enable users to find any report, feature, or data point instantly through AI-powered semantic search with natural language queries",
    compositeScore: 92,
    signalCount: 8,
    painSeverity: 9,
    hasMoneyQuotes: true,
    recencyScore: 95,
    moneyQuotes: [
      "Your competitors have AI features now. When are you catching up? - Churned customer exit interview",
      "Sales team keeps asking for better search. Lost 2 deals this quarter because prospects couldn't find features during demos.",
    ],
    sampleSignals: [
      "I can never find the report I need. Search is completely broken. - Enterprise PM",
      "Spent 20 minutes looking for last quarter's revenue breakdown. Gave up. - Sales lead",
      "40% of tickets this week are 'how do I find X'. We need better discoverability ASAP.",
    ],
    sources: ["Customer Feedback", "Internal Slack", "Support Tickets"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-2",
    runId: "mock-run",
    userId: "",
    title: "Users want conversational data access instead of click-heavy UI",
    summary: "Users express desire to ask questions about their data naturally rather than navigating complex dashboard interfaces. Current UI only exposes 10% of capabilities to average users.",
    featureSuggestion: "Enable users to ask natural language questions about their data and receive instant, contextual answers with supporting visualizations",
    compositeScore: 78,
    signalCount: 4,
    painSeverity: 7,
    hasMoneyQuotes: true,
    recencyScore: 80,
    moneyQuotes: [
      "Board is asking about our AI strategy. Competitors are shipping AI features monthly. We need to move faster.",
    ],
    sampleSignals: [
      "Would love to just ASK questions about my data instead of clicking around. - Startup founder",
      "The dashboard is powerful but I only use 10% because I can't find the rest. - Mid-market ops manager",
      "Too many clicks to get anywhere. Navigation is a maze. - Power user, 2yr customer",
    ],
    sources: ["Customer Feedback", "Internal Slack"],
    createdAt: new Date().toISOString(),
  },
  {
    id: "mock-3",
    runId: "mock-run",
    userId: "",
    title: "Declining user retention linked to poor feature discoverability",
    summary: "Product metrics show a concerning trend: search success rate is dropping, time-to-find is increasing, and 30-day retention is declining. Feature discovery rate is stuck at 23%, meaning users miss most of the product's value.",
    featureSuggestion: "Enable users to discover relevant features through contextual, proactive suggestions based on their usage patterns and goals",
    compositeScore: 65,
    signalCount: 3,
    painSeverity: 6,
    hasMoneyQuotes: false,
    recencyScore: 70,
    moneyQuotes: [],
    sampleSignals: [
      "Search Success Rate: 34%, down -8% MoM",
      "Feature Discovery Rate: 23%, flat",
      "User Retention (30d): 61%, down -4% MoM",
    ],
    sources: ["Product Metrics"],
    createdAt: new Date().toISOString(),
  },
];
